name: macOS

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: false

      - name: Setup
        run: |
          brew install automake autoconf autoconf-archive libtool texinfo yasm ninja python ccache
      - name: Restore artifacts, or setup vcpkg
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgGitCommitId: 339a9f5e1347976d69e369e4ec99e8e59d321acc

      - name: Install vcpkg packages and configure CMake
        shell: bash
        run: |
          vcpkg install
          cmake -G Ninja -D CMAKE_BUILD_TYPE=RelWithDebInfo -S . -B build
      - name: Build
        run: cmake --build build

      - name: Test
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE/build
          ctest -V