name: Windows

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: 13
          platform: x64

      - name: Restore artifacts, or setup vcpkg
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgGitCommitId: 79fa9d85cb4510b05c2657bd7ec8a6a2cb266dc5

      - name: Install vcpkg packages and configure CMake
        run: |
          vcpkg install
          cmake -D CMAKE_BUILD_TYPE=RelWithDebInfo -S . -B build
      - name: Build
        run: cmake --build build

      - name: Test
        run:  |
          cd build
          ctest -C Debug -j2 --output-on-failure